In [1]:
import pandas as pd #import pandas for dataframe operations
import numpy as np #import numpy for numerical operation
import matplotlib.pyplot as plt #import pyplot module of matplotlib
import seaborn as sns #import seaborn
#to make all plots to be displayed just below the code.
%matplotlib inline

In [2]:
df= pd.read_csv("did.csv")

/usr/local/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3361: DtypeWarning: Columns (14,21,26,27,28,34,38,40,41,44,53,54,61,62,63) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
df=  df.sample(6000)

In [4]:
df

,did_id,src_nm,src_id,drug_raw_name,cas_cas_no,cas_pt,cas_source,cas_match,chebi_pt,chebi_id,...,ind_umls_sem_typ4,ind_umls_in_term_match,ind_umls_in_term,ind_umls_in_pt,ind_umls_in_cui,ind_umls_in_term_typ,ind_umls_in_sem_typ1,ind_umls_in_sem_typ2,ind_umls_in_sem_typ3,ind_umls_in_sem_typ4
97244,2_037387,evoc_ATC,A03AB,atromepine,428-07-9,Atromepine,ChemID+,exact,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116312,2_062985,CTD,D000305,Adrenal Cortex Hormones,8001-02-3,Corticosteroids,ChemID+,<syn per source>,corticosteroid hormone,36699.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140710,2_087383,CTD,C076946,donepezil,120014-06-4,Donepezil,ChemID+,exact,donepezil,53289.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18991,1_021049,DrugBank,DB01091,Butenafine,101828-21-1,Butenafine,ChemID+,exact,butenafine,3238.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115923,2_062596,CTD,D015250,Aclarubicin,57576-44-0,Aclarubicin,ChemID+,exact,aclacinomycin A,74619.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129726,2_076399,CTD,D002740,Chlorothiazide,58-94-6,Chlorothiazide,ChemID+,exact,chlorothiazide,3640.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159889,2_106562,CTD,D008712,Methicillin,61-32-5,Methicillin,ChemID+,exact,methicillin,6827.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186062,2_132735,CTD,D013827,Thiabendazole,148-79-8,Thiabendazole,ChemID+,exact,thiabendazole,45979.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163255,2_109928,CTD,C048833,modafinil,68693-11-8,Modafinil,ChemID+,exact,modafinil,31859.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91310,2_031452,WHO_DD,L01XC,SAMALIZUMAB,1073059-33-2,samalizumab,evoc,exact,NaN,NaN,...,NaN,syn,immunomodulator,Immunomodulators,1527392.0,S,A1.4.1.1.1_Pharmacologic Substance,A1.4.1.1.3.5_Immunologic Factor,NaN,NaN

In [5]:
df.shape

(6000, 64)

In [6]:
df.head()

,did_id,src_nm,src_id,drug_raw_name,cas_cas_no,cas_pt,cas_source,cas_match,chebi_pt,chebi_id,...,ind_umls_sem_typ4,ind_umls_in_term_match,ind_umls_in_term,ind_umls_in_pt,ind_umls_in_cui,ind_umls_in_term_typ,ind_umls_in_sem_typ1,ind_umls_in_sem_typ2,ind_umls_in_sem_typ3,ind_umls_in_sem_typ4
97244,2_037387,evoc_ATC,A03AB,atromepine,428-07-9,Atromepine,ChemID+,exact,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116312,2_062985,CTD,D000305,Adrenal Cortex Hormones,8001-02-3,Corticosteroids,ChemID+,<syn per source>,corticosteroid hormone,36699.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140710,2_087383,CTD,C076946,donepezil,120014-06-4,Donepezil,ChemID+,exact,donepezil,53289.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18991,1_021049,DrugBank,DB01091,Butenafine,101828-21-1,Butenafine,ChemID+,exact,butenafine,3238.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115923,2_062596,CTD,D015250,Aclarubicin,57576-44-0,Aclarubicin,ChemID+,exact,aclacinomycin A,74619.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# i have used chunks of the data
df = pd.read_csv("did.csv", nrows=6000)

In [8]:
df.shape

(6000, 64)

In [9]:
df.head(20)

,did_id,src_nm,src_id,drug_raw_name,cas_cas_no,cas_pt,cas_source,cas_match,chebi_pt,chebi_id,...,ind_umls_sem_typ4,ind_umls_in_term_match,ind_umls_in_term,ind_umls_in_pt,ind_umls_in_cui,ind_umls_in_term_typ,ind_umls_in_sem_typ1,ind_umls_in_sem_typ2,ind_umls_in_sem_typ3,ind_umls_in_sem_typ4
0,1_000001,NDFRT,C0016157,Fish Oils,8016-13-5,Fish oil,ChemID+,<syn per source>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1_000002,NDFRT,C0016157,Fish Oils,8016-13-5,Fish oil,ChemID+,<syn per source>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1_000003,NDFRT,C0016157,Fish Oils,8016-13-5,Fish oil,ChemID+,<syn per source>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1_000004,NDFRT,C0016157,Fish Oils,8016-13-5,Fish oil,ChemID+,<syn per source>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1_000005,NDFRT,C0016157,Fish Oils,8016-13-5,Fish oil,ChemID+,<syn per source>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1_000006,MeSH_PA,D015718,Fibrin Tissue Adhesive,103170-82-7,Fibrin Tissue Adhesive,ChemID+,exact,NaN,NaN,...,NaN,exact (CUI-based),Coagulants,Coagulants,9117.0,P,A1.4.1.1.1_Pharmacologic Substance,NaN,NaN,NaN
6,1_000007,MeSH_PA,D015718,Fibrin Tissue Adhesive,103170-82-7,Fibrin Tissue Adhesive,ChemID+,exact,NaN,NaN,...,NaN,exact (CUI-based),Hematologic Agents,Hematologic Agents,18938.0,P,A1.4.1.1.1_Pharmacologic Substance,NaN,NaN,NaN
7,1_000008,MeSH_PA,D015718,Fibrin Tissue Adhesive,103170-82-7,Fibrin Tissue Adhesive,ChemID+,exact,NaN,NaN,...,NaN,exact (CUI-based),hemostatics,Hemostatic Agents,19120.0,S,A1.4.1.1.1_Pharmacologic Substance,NaN,NaN,NaN
8,1_000009,MeSH_PA,D015718,Fibrin Tissue Adhesive,103170-82-7,Fibrin Tissue Adhesive,ChemID+,exact,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1_000010,MeSH_PA,D015718,Fibrin Tissue Adhesive,103170-82-7,Fibrin Tissue Adhesive,ChemID+,exact,NaN,NaN,...,NaN,exact (CUI-based),Tissue Adhesives,Tissue Adhesives,40277.0,P,A1.4.1.1.2_Biomedical or Dental Material,NaN,NaN,NaN
10,1_000011,ChEBI,NaN,organochlorine insecticide,NaN,NaN,NaN,NaN,organochlorine insecticide,25705.0,...,NaN,exact 1,insecticide,Insecticides,21576.0,S,A1.4.1.1.5_Hazardous or Poisonous Substance,NaN,NaN,NaN
11,1_000012,ChEBI,NaN,organochlorine pesticide,NaN,NaN,NaN,NaN,organochlorine pesticide,38656.0,...,NaN,exact 1,pesticide,Pesticides,31253.0,S,A1.4.1.1.5_Hazardous or Poisonous Substance,NaN,NaN,NaN
12,1_000013,MeSH_PA,C546060,hydrated silica gel-based toothpaste,112926-00-8,Hydrated silica,ChemID+,NT app,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1_000014,MeSH_PA,C546060,hydrated silica gel-based toothpaste,112926-00-8,Hydrated silica,ChemID+,NT app,NaN,NaN,...,NaN,exact (CUI-based),Dentifrices,Dentifrices,11427.0,P,A1.4.1.1.2_Biomedical or Dental Material,NaN,NaN,NaN
14,1_000015,MeSH_PA,D019422,Dietary Sucrose,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,exact (CUI-based),flavoring agents,Flavoring,475332.0,S,A1.4_Substance,NaN,NaN,NaN
15,1_000016,MeSH_PA,D019422,Dietary Sucrose,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1_000017,MeSH_PA,D019422,Dietary Sucrose,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,exact (CUI-based),Sweetening Agents,Sweetening Agents,38998.0,P,A1.4.1.1_Chemical Viewed Functionally,NaN,NaN,NaN
17,1_000018,MeSH_PA,C003438,thiazolidine-4-carboxylic acid,444-27-9,Timonacic,ChemID+,<syn per source>,thioproline,64564.0,...,NaN,exact (CUI-based),Antidotes,Antidotes,3295.0,P,A1.4.1.1.1_Pharmacologic Substance,NaN,NaN,NaN
18,1_000019,MeSH_PA,C003438,thiazolidine-4-carboxylic acid,444-27-9,Timonacic,ChemID+,<syn per source>,thioproline,64564.0,...,NaN,exact (CUI-based),Antineoplastic Agents,Antineoplastic Agents,3392.0,P,A1.4.1.1.1_Pharmacologic Substance,A1.4.1.2.1_Organic Chemical,NaN,NaN
19,1_000020,MeSH_PA,C003438,thiazolidine-4-carboxylic acid,444-27-9,Timonacic,ChemID+,<syn per source>,thioproline,64564.0,...,NaN,exact (CUI-based),Antioxidants,Antioxidants,3402.0,P,A1.4.1.1.1_Pharmacologic Substance,NaN,NaN,NaN

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 64 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   did_id                     6000 non-null   object
 1   src_nm                     6000 non-null   object
 2   src_id                     4992 non-null   object
 3   drug_raw_name              6000 non-null   object
 4   cas_cas_no                 5629 non-null   object
 5   cas_pt                     5629 non-null   object
 6   cas_source                 5629 non-null   object
 7   cas_match                  5629 non-null   object
 8   chebi_pt                   2612 non-null   object
 9   chebi_id                   2612 non-null   float64
 10  chebi_cas_no               2322 non-null   object
 11  chebi_match                2612 non-null   object
 12  chebi_syn                  828 non-null    object
 13  chebi_syn_match            828 non-null    object
 14  chebi_match_aid            26 non-null     object
 15  chemid_pt                  5705 non-null   object
 16  chemid_display_name        2420 non-null   object
 17  chemid_id                  5704 non-null   object
 18  chemi_match                5705 non-null   object
 19  chemid_syn                 856 non-null    object
 20  chemid_syn_match           856 non-null    object
 21  chemid_match_aid           5 non-null      object
 22  ctd_pt                     5362 non-null   object
 23  ctd_mesh_id                5362 non-null   object
 24  ctd_cas_no                 4700 non-null   object
 25  ctd_match                  5362 non-null   object
 26  ctd_syn                    1303 non-null   object
 27  ctd_syn_match              1303 non-null   object
 28  ctd_match_aid              0 non-null      float64
 29  umls_pt                    6000 non-null   object
 30  umls_cui                   6000 non-null   int64
 31  umls_match                 6000 non-null   object
 32  umls_syn                   25 non-null     object
 33  umls_syn_match             25 non-null     object
 34  umls_match_aid             0 non-null      float64
 35  umls_sem_typ1              6000 non-null   object
 36  umls_sem_typ2              5496 non-null   object
 37  umls_sem_typ3              387 non-null    object
 38  umls_sem_typ4              0 non-null      float64
 39  ind_raw                    3218 non-null   object
 40  ind_agg                    878 non-null    object
 41  ind_search                 744 non-null    object
 42  ind_raw_value              6000 non-null   object
 43  ind_raw_target             6000 non-null   object
 44  ind_raw_match              4792 non-null   object
 45  ind_umls_entry_term_match  6000 non-null   object
 46  ind_umls_entry_term        6000 non-null   object
 47  ind_umls_pt                6000 non-null   object
 48  und_umls_cuii              6000 non-null   object
 49  ind_umls_term_typ          5996 non-null   object
 50  ind_umls_pheno_flg         5004 non-null   object
 51  ind_umls_sem_typ1          5996 non-null   object
 52  ind_umls_sem_typ2          87 non-null     object
 53  ind_umls_sem_typ3          3 non-null      object
 54  ind_umls_sem_typ4          0 non-null      float64
 55  ind_umls_in_term_match     4005 non-null   object
 56  ind_umls_in_term           4005 non-null   object
 57  ind_umls_in_pt             4005 non-null   object
 58  ind_umls_in_cui            4005 non-null   float64
 59  ind_umls_in_term_typ       4005 non-null   object
 60  ind_umls_in_sem_typ1       4005 non-null   object
 61  ind_umls_in_sem_typ2       554 non-null    object
 62  ind_umls_in_sem_typ3       50 non-null     object
 63  ind_umls_in_sem_typ4       0 non-null      float64
dtypes: float64(7), int64(1), object(56)
memory usage: 2.9+ MB

In [11]:
df.columns

Index(['did_id', 'src_nm', 'src_id', 'drug_raw_name', 'cas_cas_no', 'cas_pt',
       'cas_source', 'cas_match', 'chebi_pt', 'chebi_id', 'chebi_cas_no',
       'chebi_match', 'chebi_syn', 'chebi_syn_match', 'chebi_match_aid',
       'chemid_pt', 'chemid_display_name', 'chemid_id', 'chemi_match',
       'chemid_syn', 'chemid_syn_match', 'chemid_match_aid', 'ctd_pt',
       'ctd_mesh_id', 'ctd_cas_no', 'ctd_match', 'ctd_syn', 'ctd_syn_match',
       'ctd_match_aid', 'umls_pt', 'umls_cui', 'umls_match', 'umls_syn',
       'umls_syn_match', 'umls_match_aid', 'umls_sem_typ1', 'umls_sem_typ2',
       'umls_sem_typ3', 'umls_sem_typ4', 'ind_raw', 'ind_agg', 'ind_search',
       'ind_raw_value', 'ind_raw_target', 'ind_raw_match',
       'ind_umls_entry_term_match', 'ind_umls_entry_term', 'ind_umls_pt',
       'und_umls_cuii', 'ind_umls_term_typ', 'ind_umls_pheno_flg',
       'ind_umls_sem_typ1', 'ind_umls_sem_typ2', 'ind_umls_sem_typ3',
       'ind_umls_sem_typ4', 'ind_umls_in_term_match', 'ind_umls_in_term',
       'ind_umls_in_pt', 'ind_umls_in_cui', 'ind_umls_in_term_typ',
       'ind_umls_in_sem_typ1', 'ind_umls_in_sem_typ2', 'ind_umls_in_sem_typ3',
       'ind_umls_in_sem_typ4'],
      dtype='object')

In [12]:
#are there any duplicate values
df.duplicated().sum()
df

,did_id,src_nm,src_id,drug_raw_name,cas_cas_no,cas_pt,cas_source,cas_match,chebi_pt,chebi_id,...,ind_umls_sem_typ4,ind_umls_in_term_match,ind_umls_in_term,ind_umls_in_pt,ind_umls_in_cui,ind_umls_in_term_typ,ind_umls_in_sem_typ1,ind_umls_in_sem_typ2,ind_umls_in_sem_typ3,ind_umls_in_sem_typ4
0,1_000001,NDFRT,C0016157,Fish Oils,8016-13-5,Fish oil,ChemID+,<syn per source>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1_000002,NDFRT,C0016157,Fish Oils,8016-13-5,Fish oil,ChemID+,<syn per source>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1_000003,NDFRT,C0016157,Fish Oils,8016-13-5,Fish oil,ChemID+,<syn per source>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1_000004,NDFRT,C0016157,Fish Oils,8016-13-5,Fish oil,ChemID+,<syn per source>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1_000005,NDFRT,C0016157,Fish Oils,8016-13-5,Fish oil,ChemID+,<syn per source>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,1_006391,USAN_TC,NaN,edrophonium chloride,116-38-1,Edrophonium chloride,ChemID+,exact,edrophonium chloride,4759.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5996,1_006392,USAN_TC,1994,efegatran sulfate,126721-07-1,Efegatran sulfate,ChemID+,exact,NaN,NaN,...,NaN,quasi syn,Antithrombotic Agents,Antithrombotic Agents,1704311.0,P,A1.4.1.1.1_Pharmacologic Substance,NaN,NaN,NaN
5997,1_006393,USAN_TC,1986,eflornithine hydrochloride,68278-23-9,Eflornithine hydrochloride,ChemID+,exact,NaN,NaN,...,NaN,exact 1,antineoplastic,Antineoplastic Agents,3392.0,S,A1.4.1.1.1_Pharmacologic Substance,A1.4.1.2.1_Organic Chemical,NaN,NaN
5998,1_006394,MeSH_PA,C025086,"15-hydroperoxy-5,8,11,13-eicosatetraenoic acid",67675-14-3,"15-Hydroperoxy-5,8,11,13-eicosatetraenoic acid",ChemID+,exact,NaN,NaN,...,NaN,exact (CUI-based),Cardiovascular Agents,Cardiovascular Agents,7220.0,P,A1.4.1.1.1_Pharmacologic Substance,NaN,NaN,NaN
5999,1_006395,MeSH_PA,C025086,"15-hydroperoxy-5,8,11,13-eicosatetraenoic acid",67675-14-3,"15-Hydroperoxy-5,8,11,13-eicosatetraenoic acid",ChemID+,exact,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df=df.drop(['did_id','chebi_pt', 'chebi_id', 'chebi_cas_no',
       'chebi_match', 'chebi_syn', 'chebi_syn_match', 'chebi_match_aid','chemid_pt', 'chemid_display_name', 'chemid_id', 'chemi_match',
       'chemid_syn', 'chemid_syn_match', 'chemid_match_aid', 'ctd_pt',
       'ctd_mesh_id', 'ctd_cas_no', 'ctd_match', 'ctd_syn', 'ctd_syn_match',
       'ctd_match_aid','umls_match', 'umls_syn',
       'umls_syn_match', 'umls_match_aid', 'umls_sem_typ1', 'umls_sem_typ2',
       'umls_sem_typ3', 'umls_sem_typ4', 'ind_raw', 'ind_agg', 'ind_search', 'ind_umls_entry_term', 'ind_umls_pt',
       'und_umls_cuii', 'ind_umls_term_typ', 'ind_umls_pheno_flg',
       'ind_umls_sem_typ1', 'ind_umls_sem_typ2', 'ind_umls_sem_typ3',
       'ind_umls_sem_typ4', 'ind_umls_in_term_match', 'ind_umls_in_term',
       'ind_umls_in_pt', 'ind_umls_in_cui', 'ind_umls_in_term_typ',
       'ind_umls_in_sem_typ1', 'ind_umls_in_sem_typ2', 'ind_umls_in_sem_typ3',
       'ind_umls_in_sem_typ4'], axis = 1)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   src_nm                     6000 non-null   object
 1   src_id                     4992 non-null   object
 2   drug_raw_name              6000 non-null   object
 3   cas_cas_no                 5629 non-null   object
 4   cas_pt                     5629 non-null   object
 5   cas_source                 5629 non-null   object
 6   cas_match                  5629 non-null   object
 7   umls_pt                    6000 non-null   object
 8   umls_cui                   6000 non-null   int64
 9   ind_raw_value              6000 non-null   object
 10  ind_raw_target             6000 non-null   object
 11  ind_raw_match              4792 non-null   object
 12  ind_umls_entry_term_match  6000 non-null   object
dtypes: int64(1), object(12)
memory usage: 609.5+ KB

In [15]:
# how many missing values in this dataset
df.isnull().sum()

src_nm                          0
src_id                       1008
drug_raw_name                   0
cas_cas_no                    371
cas_pt                        371
cas_source                    371
cas_match                     371
umls_pt                         0
umls_cui                        0
ind_raw_value                   0
ind_raw_target                  0
ind_raw_match                1208
ind_umls_entry_term_match       0
dtype: int64

In [16]:
# missing values handel

In [17]:
m=df["src_id"].mode()
m

0    1987
dtype: object

In [18]:
#it returns a series object,conatining the most common value,we have to select the particular value in the series
m=df["src_id"].mode()[0]
m

'1987'

In [19]:
# fill in the value
df["src_id"].fillna(m,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   src_nm                     6000 non-null   object
 1   src_id                     6000 non-null   object
 2   drug_raw_name              6000 non-null   object
 3   cas_cas_no                 5629 non-null   object
 4   cas_pt                     5629 non-null   object
 5   cas_source                 5629 non-null   object
 6   cas_match                  5629 non-null   object
 7   umls_pt                    6000 non-null   object
 8   umls_cui                   6000 non-null   int64
 9   ind_raw_value              6000 non-null   object
 10  ind_raw_target             6000 non-null   object
 11  ind_raw_match              4792 non-null   object
 12  ind_umls_entry_term_match  6000 non-null   object
dtypes: int64(1), object(12)
memory usage: 609.5+ KB

In [20]:
#lets replace the null value in the cas_cas_no coulmn¶

In [21]:
m=df["cas_cas_no"].mode()
m

0    144-55-8
dtype: object

In [22]:
#it returns a series object,conatining the most common value,we have to select the particular value in the series
m=df["cas_cas_no"].mode()[0]
m

'144-55-8'

In [23]:
# fill in the value
df["cas_cas_no"].fillna(m,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   src_nm                     6000 non-null   object
 1   src_id                     6000 non-null   object
 2   drug_raw_name              6000 non-null   object
 3   cas_cas_no                 6000 non-null   object
 4   cas_pt                     5629 non-null   object
 5   cas_source                 5629 non-null   object
 6   cas_match                  5629 non-null   object
 7   umls_pt                    6000 non-null   object
 8   umls_cui                   6000 non-null   int64
 9   ind_raw_value              6000 non-null   object
 10  ind_raw_target             6000 non-null   object
 11  ind_raw_match              4792 non-null   object
 12  ind_umls_entry_term_match  6000 non-null   object
dtypes: int64(1), object(12)
memory usage: 609.5+ KB

In [24]:
#lets replace the null value in the cas_pt coulmn
m=df["cas_pt"].mode()
m

0    Sodium bicarbonate
dtype: object

In [25]:
#it returns a series object,conatining the most common value,we have to select the particular value in the series
m=df["cas_pt"].mode()[0]
m

'Sodium bicarbonate'

In [26]:
# fill in the value
df["cas_pt"].fillna(m,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   src_nm                     6000 non-null   object
 1   src_id                     6000 non-null   object
 2   drug_raw_name              6000 non-null   object
 3   cas_cas_no                 6000 non-null   object
 4   cas_pt                     6000 non-null   object
 5   cas_source                 5629 non-null   object
 6   cas_match                  5629 non-null   object
 7   umls_pt                    6000 non-null   object
 8   umls_cui                   6000 non-null   int64
 9   ind_raw_value              6000 non-null   object
 10  ind_raw_target             6000 non-null   object
 11  ind_raw_match              4792 non-null   object
 12  ind_umls_entry_term_match  6000 non-null   object
dtypes: int64(1), object(12)
memory usage: 609.5+ KB

In [27]:
#lets replace the null value in the cas_source coulmn¶

In [28]:
m=df["cas_source"].mode()
m

0    ChemID+
dtype: object

In [29]:
#it returns a series object,conatining the most common value,we have to select the particular value in the series
m=df["cas_source"].mode()[0]
m

'ChemID+'

In [30]:
# fill in the value
df["cas_source"].fillna(m,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   src_nm                     6000 non-null   object
 1   src_id                     6000 non-null   object
 2   drug_raw_name              6000 non-null   object
 3   cas_cas_no                 6000 non-null   object
 4   cas_pt                     6000 non-null   object
 5   cas_source                 6000 non-null   object
 6   cas_match                  5629 non-null   object
 7   umls_pt                    6000 non-null   object
 8   umls_cui                   6000 non-null   int64
 9   ind_raw_value              6000 non-null   object
 10  ind_raw_target             6000 non-null   object
 11  ind_raw_match              4792 non-null   object
 12  ind_umls_entry_term_match  6000 non-null   object
dtypes: int64(1), object(12)
memory usage: 609.5+ KB

In [31]:
#lets replace the null value in the cas_match coulmn¶

In [32]:
m=df["cas_match"].mode()
m

0    exact
dtype: object

In [33]:
#it returns a series object,conatining the most common value,we have to select the particular value in the series
m=df["cas_match"].mode()[0]
m

'exact'

In [34]:
# fill in the value
df["cas_match"].fillna(m,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   src_nm                     6000 non-null   object
 1   src_id                     6000 non-null   object
 2   drug_raw_name              6000 non-null   object
 3   cas_cas_no                 6000 non-null   object
 4   cas_pt                     6000 non-null   object
 5   cas_source                 6000 non-null   object
 6   cas_match                  6000 non-null   object
 7   umls_pt                    6000 non-null   object
 8   umls_cui                   6000 non-null   int64
 9   ind_raw_value              6000 non-null   object
 10  ind_raw_target             6000 non-null   object
 11  ind_raw_match              4792 non-null   object
 12  ind_umls_entry_term_match  6000 non-null   object
dtypes: int64(1), object(12)
memory usage: 609.5+ KB

In [35]:
# lets replace the null value in the ind_raw_match coulmn

In [36]:
m=df["ind_raw_match"].mode()
m

0    True
dtype: object

In [37]:
#it returns a series object,conatining the most common value,we have to select the particular value in the series
m=df["ind_raw_match"].mode()[0]
m

True

In [38]:
# fill in the value
df["ind_raw_match"].fillna(m,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   src_nm                     6000 non-null   object
 1   src_id                     6000 non-null   object
 2   drug_raw_name              6000 non-null   object
 3   cas_cas_no                 6000 non-null   object
 4   cas_pt                     6000 non-null   object
 5   cas_source                 6000 non-null   object
 6   cas_match                  6000 non-null   object
 7   umls_pt                    6000 non-null   object
 8   umls_cui                   6000 non-null   int64
 9   ind_raw_value              6000 non-null   object
 10  ind_raw_target             6000 non-null   object
 11  ind_raw_match              6000 non-null   bool
 12  ind_umls_entry_term_match  6000 non-null   object
dtypes: bool(1), int64(1), object(11)
memory usage: 568.5+ KB

In [39]:
#all missing data is filled now lets implement label encoding on input variable

In [40]:
df.shape

(6000, 13)

In [41]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

In [42]:
df["src_nm"]=le.fit_transform(df["src_nm"])

In [43]:
df["src_id"]=le.fit_transform(df["src_id"])

In [44]:
df["cas_cas_no"]=le.fit_transform(df["cas_cas_no"])

In [45]:
df["cas_pt"]=le.fit_transform(df["cas_pt"])

In [46]:

df["cas_source"]=le.fit_transform(df["cas_source"])

In [47]:

df["cas_match"]=le.fit_transform(df["cas_match"])

In [48]:

df["umls_pt"]=le.fit_transform(df["umls_pt"])

In [49]:
df["umls_cui"]=le.fit_transform(df["umls_cui"])

In [50]:

df["ind_raw_value"]=le.fit_transform(df["ind_raw_value"])

In [51]:

df["ind_raw_target"]=le.fit_transform(df["ind_raw_target"])

In [52]:

df["ind_raw_match"]=le.fit_transform(df["ind_raw_match"])

In [53]:

df["ind_umls_entry_term_match"]=le.fit_transform(df["ind_umls_entry_term_match"])

In [54]:
df.head()

,src_nm,src_id,drug_raw_name,cas_cas_no,cas_pt,cas_source,cas_match,umls_pt,umls_cui,ind_raw_value,ind_raw_target,ind_raw_match,ind_umls_entry_term_match
0,4,291,Fish Oils,1442,1353,2,0,1568,96,126,152,0,13
1,4,291,Fish Oils,1442,1353,2,0,1568,96,128,154,0,13
2,4,291,Fish Oils,1442,1353,2,0,1568,96,250,304,0,13
3,4,291,Fish Oils,1442,1353,2,0,1568,96,329,376,0,13
4,4,291,Fish Oils,1442,1353,2,0,1568,96,331,378,0,13

In [55]:
df.to_csv('final_soltion_drugdata.csv')

# First, you separate the columns into dependent and independent variables (or features and labels). Then you split those variables into a training and test set.

In [56]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

X=df[['src_nm', 'src_id', 'cas_cas_no', 'cas_pt','cas_source','cas_match','umls_pt','umls_cui','ind_raw_value','ind_raw_target','ind_raw_match','ind_umls_entry_term_match']]  # Features
y=df['drug_raw_name']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) # 80% training and 30% test

In [57]:
X_train

,src_nm,src_id,cas_cas_no,cas_pt,cas_source,cas_match,umls_pt,umls_cui,ind_raw_value,ind_raw_target,ind_raw_match,ind_umls_entry_term_match
4909,0,97,125,1002,2,17,1201,1773,918,822,0,21
1226,3,1044,175,834,2,0,200,903,612,543,0,22
1504,3,1122,349,1621,2,4,17,1072,497,417,0,13
272,3,522,931,1619,2,13,1863,838,476,389,0,13
2379,3,463,896,341,2,13,457,395,164,201,0,21
...,...,...,...,...,...,...,...,...,...,...,...,...
5857,5,97,244,1287,2,13,1505,1466,557,482,0,21
2133,3,471,620,202,2,13,269,284,161,198,0,21
2460,3,610,883,398,2,13,535,438,623,554,0,22
4256,0,97,1146,840,2,13,1034,1410,978,924,0,14
1417,3,872,1328,751,2,0,574,462,466,386,0,22

In [58]:
X_test

,src_nm,src_id,cas_cas_no,cas_pt,cas_source,cas_match,umls_pt,umls_cui,ind_raw_value,ind_raw_target,ind_raw_match,ind_umls_entry_term_match
3384,3,944,193,572,2,13,743,526,476,389,0,13
4817,1,169,805,973,2,13,1172,1028,377,1221,0,20
231,3,571,1102,220,2,13,294,305,256,310,0,13
1310,3,1065,159,194,2,13,257,860,497,417,0,13
1730,3,854,1588,1405,2,13,1650,714,626,557,0,21
...,...,...,...,...,...,...,...,...,...,...,...,...
1564,3,756,1467,1435,2,13,1653,717,111,136,0,21
2759,3,591,1207,1451,2,13,1672,733,104,129,0,21
5642,3,1351,1459,1232,2,12,1448,85,78,102,0,21
4710,6,87,1021,951,2,13,1148,1881,863,775,0,21
948,3,1151,207,1463,2,13,1687,1546,60,84,0,21

In [59]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=200)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [60]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7933333333333333

In [61]:

clf.predict([[6, 84, 376, 606,2,13,779,1461,98,944,0,20]])

/usr/local/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array(['besipirdine hydrochloride'], dtype=object)

# implementing extra tree regresseor

In [62]:
# lets implement label encoding on target column
df["drug_raw_name"]=le.fit_transform(df["drug_raw_name"])
df

,src_nm,src_id,drug_raw_name,cas_cas_no,cas_pt,cas_source,cas_match,umls_pt,umls_cui,ind_raw_value,ind_raw_target,ind_raw_match,ind_umls_entry_term_match
0,4,291,788,1442,1353,2,0,1568,96,126,152,0,13
1,4,291,788,1442,1353,2,0,1568,96,128,154,0,13
2,4,291,788,1442,1353,2,0,1568,96,250,304,0,13
3,4,291,788,1442,1353,2,0,1568,96,329,376,0,13
4,4,291,788,1442,1353,2,0,1568,96,331,378,0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,6,97,1789,143,1323,2,13,1542,91,883,794,0,12
5996,6,104,1790,226,1324,2,13,1543,1523,936,838,0,21
5997,6,96,1791,1234,1325,2,13,1544,1154,915,821,0,21
5998,3,642,133,1224,102,2,13,131,197,164,201,0,21
5999,3,642,133,1224,102,2,13,131,197,235,286,0,13

# ExtraTrees Classifier is an ensemble method which is much faster than RandomForest yet equall accurate

before looking at what an extra tree classifier is lets first look at random forest works letts consider a simple data set n features and n raws in a random forest we run multiple trees that each tree comprise of the squre roo of the total number of features that are persent so in our case we have n features so each tree would have square root of n features to train on additionally we will be making use of bootstarp samples or samples with replacemnets that is where we have the out of the bag error score that we can use later on for validation


### How is an extra 3 classified different

the very first difference of an extra tree classifier lies in how we select samples in extra tree classifer,we will be selecting samples for every decision tree without replacemnt so all the samples would be unique in nature.
the total number of fetaures selected still remain the same that is square root of the total number of features if you are using a classsification task



### so what exactly differnce between  random forest and extra tree classifier

lies in the fact that instead of computing the locally optimal split for a feature combination a random value is selectd for the split for the extra tree  so again the whole idea is rather that not spending time and finding out the best splitting point.

i randomly pick up a point and split based on that this leads to more diversified trees and less splitters to avalute when training and extremely random forest.

when extra tree classifiers where tested with the raedily available data sets, we oberved that when we had mnoisy features in our data set extra tree classifires seemed to outperform random forest however wehn all the features are relevent and when you train both extra tree classifers as well as a random forest both methods seem to have achived the same performance be it in terms of accuracy, AUC,ROC values or the f1 score that we are closing

In [63]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

X=df[['src_nm', 'src_id', 'cas_cas_no', 'cas_pt','cas_source','cas_match','umls_pt','umls_cui','ind_raw_value','ind_raw_target','ind_raw_match','ind_umls_entry_term_match']]  # Features
y=df['drug_raw_name']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) # 80% training and 30% test

In [64]:
#Preparing Extra Tree Regression
from sklearn.ensemble import  ExtraTreesRegressor
ET_Model=ExtraTreesRegressor(n_estimators = 120)


ET_Model.fit(X_train,y_train)
y_predict=ET_Model.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_predict)

0.9891428397824483

In [65]:

ET_Model.predict([[6, 84, 376, 606,2,13,779,1461,98,944,0,20]])

/usr/local/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but ExtraTreesRegressor was fitted with feature names
  warnings.warn(

array([1091.34166667])

preceion 
f1 score 

try xg boost on this dataset
ann will try to use

In [66]:
le.classes_

array(['(1R-(exo,exo))-3-(4-fluorophenyl)-8-methyl-8- azabicyclo(3.2.1)octane-2-carboxylic acid, methyl ester',
       "(2',5'-bis-O-(tert-butyldimethylsilyl)-beta-ribofuranosyl)-3'-spiro-5''-(4''-amino-1'',2''-oxathiole-2'',2''-dioxide)thymine",
       "(2-(2',6'-dimethoxy)phenoxyethylamino)methylbenzo-1,4-dioxane",
       ..., 'tyrosyl-isoleucyl-glycyl-seryl-arginine',
       'valyl-leucyl-lysine 4-nitroanilide', 'zeta Carotene'],
      dtype=object)

In [67]:
# we can inverse transform 
le.inverse_transform([1091])

array(['ammonium sulfate'], dtype=object)